
---
<!-- output: "pdf_document -->"
<!-- documentclass: "report -->"
<!-- geometry: "margin=.5in -->"
<!-- fontsize: "11pt -->"
<!-- font: "Atkinson -->"
output: pdf_document
---

```{r setup, include=FALSE}
options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

options(knitr.table.format = "latex",
        knitr.kable.NA = '')


data <- sc_enhancements %>%
  filter(`Service` == a)

description <- data$`Enhancement Proposal`
```

*The Bureau of the Budget and Management Research Enhancement Proposals*

### Agency: `r agency`

**Enhancement Description**: 

`r cat(description)`


```{r budget_summary, results = 'asis'}
##replace budget data source
# data %>%
#   filter(`Service ID` == id) %>%
#   select(`Service ID`, `FY22 General Fund`:`FY24 Request_All Other Funds`) %>%
#   format_table_numbers() %>%
#   knitr::kable(format = "latex", escape = TRUE, booktabs = TRUE) %>%
#   kable_styling(latex_options = "striped")

output <- data$`Enhancement Budget` 

cat(output)

```


### Service Questions and Responses

#### Performance Impact

```{r perf, results = 'asis'}

output <-data$`Performance Impact`

print(output)

```

#### Advancing the Mayor's Action Plan

```{r MAP, results = 'asis'}

output <- data$`Advancing the Mayor's Action Plan`

cat(output)

```

#### Workload and Service Delivery

```{r workload, results = 'asis'}

output <- data$`Workload and Service Delivery Demands`

cat(output)

```

#### Equity and Resiliency

```{r proposals, results = 'asis'}

output <- data$`Equity and Resiliency`

cat(output)

```

